-- MySQL Script generated by MySQL Workbench
-- Tue Nov 30 10:37:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vizio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vizio` ;

-- -----------------------------------------------------
-- Schema vizio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vizio` DEFAULT CHARACTER SET utf8 ;
USE `vizio` ;

-- -----------------------------------------------------
-- Table `vizio`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizio`.`user` ;

CREATE TABLE IF NOT EXISTS `vizio`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NULL,
  `prenom` VARCHAR(50) NULL,
  `mdp` VARCHAR(30) NULL,
  `mail` VARCHAR(70) NULL,
  `date_n` DATE NULL,
  `sexe` ENUM('f', 'h') NULL,
  `tel` CHAR(10) NULL,
  `statut` ENUM('med', 'pat') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizio`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizio`.`document` ;

CREATE TABLE IF NOT EXISTS `vizio`.`document` (
  `id` INT(11) NOT NULL,
  `doc` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `doc_idx` (`doc` ASC),
  CONSTRAINT `doc`
    FOREIGN KEY (`doc`)
    REFERENCES `vizio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizio`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizio`.`questions` ;

CREATE TABLE IF NOT EXISTS `vizio`.`questions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(500) NULL,
  `rep1` VARCHAR(45) NULL,
  `rep2` VARCHAR(45) NULL,
  `rep3` VARCHAR(45) NULL,
  `rep4` VARCHAR(45) NULL,
  `rep5` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizio`.`quest/rep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizio`.`quest/rep` ;

CREATE TABLE IF NOT EXISTS `vizio`.`quest/rep` (
  `id` INT(11) NOT NULL,
  `quest` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `quest_idx` (`quest` ASC),
  CONSTRAINT `quest`
    FOREIGN KEY (`quest`)
    REFERENCES `vizio`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `vizio`.`pre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizio`.`pre` ;

CREATE TABLE IF NOT EXISTS `vizio`.`pre` (
  `is` INT(11) NOT NULL AUTO_INCREMENT,
  `user` INT(11) NULL,
  `quest_rep` INT(11) NULL,
  PRIMARY KEY (`is`),
  INDEX `user_idx` (`user` ASC),
  INDEX `quest/rep_idx` (`quest_rep` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `vizio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quest_rep`
    FOREIGN KEY (`quest_rep`)
    REFERENCES `vizio`.`quest/rep` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizio`.`consultation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizio`.`consultation` ;

CREATE TABLE IF NOT EXISTS `vizio`.`consultation` (
  `id` INT(11) NOT NULL,
  `date` DATETIME NULL,
  `description` VARCHAR(5000) NULL,
  `type` VARCHAR(45) NULL,
  `user2` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user2` ASC),
  CONSTRAINT `user2`
    FOREIGN KEY (`user2`)
    REFERENCES `vizio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizio`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizio`.`post` ;

CREATE TABLE IF NOT EXISTS `vizio`.`post` (
  `is` INT(11) NOT NULL AUTO_INCREMENT,
  `quest/rep` INT(11) NULL,
  `consultation` INT(11) NULL,
  PRIMARY KEY (`is`),
  INDEX `quest/rep_idx` (`quest/rep` ASC),
  INDEX `consultation_idx` (`consultation` ASC),
  CONSTRAINT `quest/rep`
    FOREIGN KEY (`quest/rep`)
    REFERENCES `vizio`.`quest/rep` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `consultation`
    FOREIGN KEY (`consultation`)
    REFERENCES `vizio`.`consultation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

